### ISSUE TITLE
Install Request: Margaret Fuller

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#102]
URL: fullerarchive.northeastern.edu

Protected while under construction: Yes

Base URL: https://repository.library.northeastern.edu/collections/neu:cj82rh63r (updated)

**Comment by sarahjeansweeney** [comment]
Base URL can be set as: https://repository.library.northeastern.edu/collections/neu:cj82rh63r

**Comment by KarlYee** [comment]
O.k.  The site is configured as requested and is up and running.

**Comment by sarahjeansweeney** [comment]
Looks good, Karl - thanks!
