### ISSUE TITLE
Switching between the Visual and Text tab when editing a post strips the <p> tags

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#103]
Switching between the Visual and Text tab when editing a post strips the `<p> `tags. This was first reported by the ECDA team and I haven't been able to replicated it on other sites, just their site.

To replicate:
Open a blog post on the ECDA site:
![2018-08-01_1524-1](https://user-images.githubusercontent.com/4663073/43544159-17a941d8-95a0-11e8-958e-2c7572f6927c.png)
Click edit to view the post text
![2018-08-01_1524](https://user-images.githubusercontent.com/4663073/43544170-1f584f3c-95a0-11e8-9d03-58caaccf633a.png)
Switch to the Visual tab (or the text tab, whichever tab you didn't land on when you opened the post)
![2018-08-01_1528](https://user-images.githubusercontent.com/4663073/43544231-4466e0e0-95a0-11e8-8e49-c50bb90e0bbb.png)
Without making any changes, preview the post
![2018-08-01_1529-1](https://user-images.githubusercontent.com/4663073/43544359-a612c43a-95a0-11e8-8bed-ecc22bc84d77.png)
Just switching between tabs strips the `<p>` tag from the post and turns the post text in to one long paragraph

**Comment by AmandaRust** [comment]
WP issue, forums say it's a notfix for them
