### ISSUE TITLE
Creator sort does not appear to change sort order in search or browse results

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#106]
The "Creator A-Z" and "Creator Z-A" sort by options do not appear to change the sort order in browse or search results. Selecting either creator sort updates the page, but retains the sort order from the last selection. To replicate:

- Go to any CERES search or browse page
- Use the "Sort by" box to update the sort order to "Title Z-A"
![2018-08-08_1522](https://user-images.githubusercontent.com/4663073/43859721-74e317aa-9b1f-11e8-9db6-c957ebeeb8c9.png)
- Use the "Sort by" box again to change the sort order to either "Creator A-Z" or "Creator Z-A"
- The "Loading..." message will quickly appear and the updated page will contain results sorted by the last sort order, "Title Z-A"
![2018-08-08_1522-1](https://user-images.githubusercontent.com/4663073/43859777-ae60a97a-9b1f-11e8-97b1-b272cfc2c520.png)

The other sort orders appear to work as expected.

**Comment by mmwoods2019** [comment]
I tried this on the Toolkittraining Search page and I had the same issue. There was no difference from the previous sort order when switching to "Creator A-Z" or "Creator Z-A."

I tried this on a MAC with Chrome (Version 69.0.3497.100)
