### ISSUE TITLE
Audio and video files not playing in CERES

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#107]
It was reported to me that the audio and video files in the Recording Studios CERES site are displaying as static images: https://recordingstudios.library.northeastern.edu/video

![2018-08-15_1437](https://user-images.githubusercontent.com/4663073/44166247-e14a0d80-a098-11e8-8424-c603176bceaa.png)

The two video exhibits in that screenshot, Flash Paper and Kaleidoscope, were created using toolkit shortcodes, so the video should play for those two items:

`[drstk_single id="neu:cj82px10v" image-size="4" display-video="true" display-issuu="true" align="center" float="none" caption-align="left" caption-position="below" zoom="on" zoom-position="1"]`

The item pages for those items also do not play as expected (there should be a play button in the middle of the thumbnail): https://recordingstudios.library.northeastern.edu/item/neu:cj82px10v

![2018-08-15_1440](https://user-images.githubusercontent.com/4663073/44166408-574e7480-a099-11e8-9d2e-33b8035d2e5a.png)

The same file does play in the DRS: https://repository.library.northeastern.edu/files/neu:cj82px10v
![2018-08-15_1442](https://user-images.githubusercontent.com/4663073/44166447-69301780-a099-11e8-859c-42f596ec8efb.png)

I was able to replicate this in different browsers (Chrome, Firefox, and Safari) and in different CERES sites:

https://latinjewisharts.northeastern.edu/interviews
https://whatsnewpodcast.org/
https://holocaustawarenessarchives.northeastern.edu/home-2/annualevents/morton-lecture/

**Comment by nestochan** [comment]
@sarahjeansweeney this was addressed in David's patch right?
can you let karl know which sites still need deployment for the patch assume phoenix is on this list as well

🃏 -e

**Comment by sarahjeansweeney** [comment]
@nestochan I believe it was. I think @dgcliff also mentioned that caching needs to be addressed.

In addition to the sites listed above, the following sites also use A/V material:
https://marathon.library.northeastern.edu/
https://phoenix.library.northeastern.edu/
https://infoliteracy.library.northeastern.edu/

There may be more, but those are the sites I know for sure contain streaming A/V

**Comment by sarahjeansweeney** [comment]
I believe this has been resolved. Please reopen if more work needs to be done.
