### ISSUE TITLE
White screen of death for multiple users: security lockout

### ISSUE THREAD

**Issue by AmandaRust** [NEU-DSG/toolkit_requests#113]
Site: publichistory.library.northeastern.edu

During a class session 9/20, about 30 students were able to log into the website, but another 5-7 were locked out. It looks like simultaneous users from similar IPs triggered a security block.

Ernesto did some investigation: "it appears you had about 5 distinct IPs blocked by WP security plugin, so that may be the issue. I would have them try again, and if possible if you need to reset their passwords do so. Also have them use incognito mode or clear the cookies that reference the publichistory site."

I also just noticed an email in my junk mail, from iThemes, with not much more detail, but giving the IP address:

![image](https://user-images.githubusercontent.com/10200332/46020547-a03c1480-c0ac-11e8-872f-8e80b6fbe1c0.png)

We have multiple follow-up work sessions with this class where 35-ish students will be logging on and working at once. Is there anything we can change in iThemes to make that safe? I've looked at the settings but don't want to monkey around in there all by myself.

**Comment by KarlYee** [comment]
I doubled the threshold before lockouts kick in.  Perhaps we can configure it to just log lockout triggers rather actually locking people out.
