### ISSUE TITLE
Upload lag on publichistory.library.northeastern.edu

### ISSUE THREAD

**Issue by AmandaRust** [NEU-DSG/toolkit_requests#114]
During 9/20 class some students were unable to upload images due to a site hangup: students would try to upload an item to the media gallery and the site would hang and never recover. This was during a class session when 35-ish students were all working in the site at once.

Is there anything we can do (increase site RAM?) to make sure that multiple concurrent uploads don't cause that kind of hang up? This class has multiple work sessions devoted to their CERES project, so will have additional times throughout the semester when all 35 will be working at once.

**Comment by KarlYee** [comment]
Hi Amanda-
Sorry that you're experiencing these issues.  I checked the PHP configuration parameters and they're high as is:

memory_limit = 550M (the default is 128M)
upload_max_filesize = 270M (default 2M)
post_max_size = 270M (default 8M)
max_execution_time = 60 
max_input_time = 60

My gut feeling is that the site is not designed to handle 35 concurrent uploads.  There is a JavaScript library available to provide  " .... multiple *simultaneous*, stable, fault-tolerant and resumable/restartable file uploads via the HTML5 File API..."  (http://qnimate.com/flow-js-awesome-library-to-work-with-html5-file-api-ajax-uploads/ ).  However, that's something for a web developer to ponder.

On an up note,  I did turn on the WP Super Cache plugin.  It's unlikely to solve this particular problem but you should see an overall bump in performance.

**Comment by patrickmj** [comment]
Wow. That certainly shoots down my guess that it was a PHP setting. That's pretty huge `upload_max_filesize` and `post_max_size` values. Unless students are uploading "The Lord of the Rings", it's hard to imagine getting above those. Only hedge I'll put on that is whether there's a directory-specific `plugin.ini` file that might be more restrictive. Feels unlikely, but I've seen that happen before.

**Comment by KarlYee** [comment]
A couple of things ...  We put in a request (SN ticket #INC0482549) with Campus ITS to bump up the RAM on the VM to 16GB, current we have 8GB.  I doubt it fix this particular problem, but it'll help w/ overall performance for the CERES sites on this machine.

As for uploads ...
I think the key issue here is "concurrent upload" and with the size of the upload.

**Comment by KarlYee** [comment]
Ernesto brought up a good point.  Assuming this is indeed the "fix", what will impact be of having 35 or 40 upload files simultaneously?  What will the impact be for the sever, the other CERES sites, other users, etc?

The default for "max_file_uploads" is 20.   So Amanda's class already tested the impact of 20 concurrent uploads, at least it's an initial test.
