### ISSUE TITLE
Page Builder needs a new name

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#12]
Users get confused between our Page Builder and the one in Wordpress, especially because the WP page builder has a "tour" it gives users a pop-up for.  Can we rename ours or make it somehow less confusing?

**Comment by elizoller** [comment]
We can rename the Page Builder if you want. I tried to hide most of the places the tours and popups about the other page builder- where are you still seeing them?

**Comment by ablevesque** [comment]
Not sure - this came in through a set of Greg and Param's old meeting notes, so it may be fixed already. Let me check with them and then if it's resolved I'll close the ticket.
