### ISSUE TITLE
WP single item display in CERES theme: caption in abstract

### ISSUE THREAD

**Issue by AmandaRust** [NEU-DSG/toolkit_requests#120]
On the public history site using the CERES theme, when items are uploaded to the WP media library there is an option to include either captions or descriptions. On display (see below) only titles and "abstract/description" are displayed. What is displayed in that field is actually the caption, when it would make the most sense for the user to display what they've entered into the description field. With the item below, in the media library we added text into both fields to try to figure out what was happening. If you remove the text from caption, you'll see that the item display lacks an "abstract/description."

https://publichistory.library.northeastern.edu/item/wp:1321/

**Comment by patrickmj** [comment]
This looks at first blush like something odd happening in the `$data->post_excerpt` data in these lines

https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/blob/master/inc/item.php#L17-L22

Will have to track down how/where that `$data`  object is put together.
