### ISSUE TITLE
Embedded DRS media items not displaying in CERES

### ISSUE THREAD

**Issue by AmandaRust** [NEU-DSG/toolkit_requests#121]
Reported by Debra Mandel, thumbnails for the media items on their website:
https://recordingstudios.library.northeastern.edu/video

Are not showing up. If you click on the "broken link" image, you get to the correct full item page on that site. But, for some reason, the items aren't showing up on the listing page.  Molly also noted that this is happening on the Lower Roxbury History site:
https://roxbury.library.northeastern.edu/lowell/

If you hover around the page, you'll see empty blocks where there should be items. Click on those empty blocks, you get to the correct single item page. 

![image](https://user-images.githubusercontent.com/10200332/47455509-09906f80-d7a0-11e8-927e-235f028e1032.png)
![image](https://user-images.githubusercontent.com/10200332/47455530-1319d780-d7a0-11e8-9987-09b3b58c2fdf.png)
![image](https://user-images.githubusercontent.com/10200332/47455541-1b721280-d7a0-11e8-9f9d-b3603f6d17f8.png)

**Comment by patrickmj** [comment]
Is this a new development (for either site), or has this always been the case?

**Comment by AmandaRust** [comment]
This is a new development.

Amanda Rust
Assistant Director, Digital Scholarship Group
Digital Humanities Librarian
Northeastern University Libraries
a.rust@northeastern.edu / 617-373-8548

________________________________

**Comment by dgcliff** [comment]
Same issue as https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/issues/129 - This should be fixed across all sites now.
