### ISSUE TITLE
Timeline not displaying

### ISSUE THREAD

**Issue by s-payne** [NEU-DSG/toolkit_requests#122]
When I try to insert a timeline shortcode, nothing appears. See the test below:

I selected items from the DRS
![screen shot 2018-11-08 at 10 26 47 am](https://user-images.githubusercontent.com/30182432/48208514-015c3680-e341-11e8-8571-109b69dc10c5.png)

Set the start and end dates
![screen shot 2018-11-08 at 10 27 15 am](https://user-images.githubusercontent.com/30182432/48208581-218bf580-e341-11e8-8c07-0b8b293ec804.png)

Insert shortcode, save changes, but then just have a big white space where the timeline should be

![screen shot 2018-11-08 at 10 31 56 am](https://user-images.githubusercontent.com/30182432/48208783-94956c00-e341-11e8-8c14-b957510ab702.png)

**Comment by patrickmj** [comment]
Could you give a link to a page where the timeline should be showing up, but isn't? Thanks.

**Comment by patrickmj** [comment]
Might also help if you give an estimate of how many items you are adding

**Comment by s-payne** [comment]
Here's the link to the page: https://decodingthearchive.northeastern.edu/exhibit-title/

I'm just trying to add 4-5 items as a test.

**Comment by patrickmj** [comment]
Thanks. But, when I follow the link, I get a Page Not Found error. Is the page published / are you logged in when you try to view the timeline?

**Comment by s-payne** [comment]
Oops, accidentally had it private. You should be able to view it now.

**Comment by patrickmj** [comment]
@s-payne Thanks....things definitely look weird in the HTML! I have a suspicion that it might be related to the maps problem, but that's just a hunch. It's worth trying what happens if you remove the shortcode for the map, though. 
If that doesn't do it, could you give me admin access to the site so I can see how that page is getting put together? Thanks!

**Comment by s-payne** [comment]
The timeline does work if you remove the map shortcode. I gave you admin access if you still want to look at it.

**Comment by patrickmj** [comment]
Progress! Next I'll try to figure out the map issue. It looks like something that's come up elsewhere, so I have a couple working theories to try.
