### ISSUE TITLE
Cache issue with image display again?

### ISSUE THREAD

**Issue by AmandaRust** [NEU-DSG/toolkit_requests#123]
https://litdigitaldiversity.northeastern.edu/women-in-computing/
https://litdigitaldiversity.northeastern.edu/archives/sample-archival-exhibit/

This might be related to the earlier problems with cached images and display and go away on its own -- but just in case! The pages above and others on the Lit & Digital Diversity website are not displaying their items, even with a hard refresh, using Chrome.

I'm tagging these as critical because we'll need those pages for Sarah C.'s class next Monday. 

![image](https://user-images.githubusercontent.com/10200332/48443107-16c8ca80-e75e-11e8-88a6-71f1a77c77d5.png)

![image](https://user-images.githubusercontent.com/10200332/48443262-7fb04280-e75e-11e8-8bc3-338e53792385.png)

**Comment by patrickmj** [comment]
These look a little weirder than cache issues. The images from DPLA are hopefully just our same DPLA issue, for which I'll have to see if I can hard-code in the fix.

The timeline issue on the sample page looks similar to the timeline issues that have cropped up recently elsewhere, so those'll will have to get some extra special attention quickly!
