### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by gregjp48** [NEU-DSG/toolkit_requests#13]
Would it be possible to make a search bar, on the level of the other navigation items, that minimizes in the way that Northeastern's main page has and expands on mouseover (screenshot below)? This would help in making it clear that browse and search are separate functions; right now, it looks like the search bar is part of the browse page when you load it, even though it's a global feature.

![screen shot 2015-11-23 at 2 28 08 pm](https://cloud.githubusercontent.com/assets/15876759/11347309/d3c0d074-91ee-11e5-9ab8-ba19c0be7df1.jpg)
![screen shot 2015-11-23 at 2 28 16 pm](https://cloud.githubusercontent.com/assets/15876759/11347310/d3ce2e0e-91ee-11e5-91b2-220b00b2c85b.jpg)

**Comment by elizoller** [comment]
I can move the search bar up in the gray bar with the hover action.
Do we want this across all sites?

**Comment by gregjp48** [comment]
Sarah and I were talking about how that might suggest the user is searching Northeastern and not just the site at hand. And there doesn't seem to be space anywhere else, at least on the Sadow site (and, I would imagine, any with more than a couple menu items). We discussed possibly wrapping a menu item to the line with the search bar the way it is right now in Irator. Ideally this would be "collections" (which would suggest "okay, now i'm about to search collections"), but the Sadow site doesn't make use of multiple collections because of its size. Param and I will have to meditate on how to better visually separate the search bar while keeping its position consistent.
