### ISSUE TITLE
Related content search giving a second page with no results

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#14]
![image](https://cloud.githubusercontent.com/assets/13038927/11347343/f5bd97e8-91ee-11e5-97a8-d87ceaf51638.jpg)
![image](https://cloud.githubusercontent.com/assets/13038927/11347344/f5c3a1ce-91ee-11e5-91cf-e9a40f9e88de.jpg)

When searched on latinamericanartists.northeastern.edu, related content said it had two pages of results. When  you click to get that second page, it says "Your query produced no results." 

I was specifically searching for Ricardo, but I have a feeling it's not related to the search.

**Comment by elizoller** [comment]
fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/1047250f884054023072483fa32e8475fab30ccf
