### ISSUE TITLE
DRS Toolkit Plugin in Plugins list

### ISSUE THREAD

**Issue by decampda** [NEU-DSG/toolkit_requests#16]
As of right now the DRS Toolkit Plugin appears on the Plugins page on the admin side of Wordpress. On that page, like with most plugins, admins have the option of Deactivating or Editing their plugins. Since every one of these sites is created specifically for using this toolkit, can we disable the "Deactivate" and "Edit" options? 

<img width="1137" alt="plugins" src="https://cloud.githubusercontent.com/assets/4481739/11482626/e0cd4792-9771-11e5-8ded-1e571eac65cd.png">

**Comment by elizoller** [comment]
fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-theme/commit/ca02c37c02f268f2d0702d97c4e4055868dde727
