### ISSUE TITLE
Video posters not loading in Firefox

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#17]
Patrick and I noticed that the video poster images aren't loading for videos in Firefox. This file for example: http://latinamericanartists.northeastern.edu/item/neu:rx914q231

![2015-12-02_1617](https://cloud.githubusercontent.com/assets/4663073/11544515/438df986-9910-11e5-8206-3ac1c8844190.png)

The video plays just fine.
The poster does load in Chrome and Safari.
I'm using Firefox 42.0 for Mac on El Capitan.

**Comment by elizoller** [comment]
I'm not able to reproduce this in FF 42.0 / El Capitan
If you have a minute today or tomorrow can I look at it on your computer?

**Comment by sarahjeansweeney** [comment]
Oddly enough, it's working for me now. I guess it was temporary.

**Comment by elizoller** [comment]
Ok. Let me know if it happens again
