### ISSUE TITLE
Full width on site title and site nav in two separate rows

### ISSUE THREAD

**Issue by elizoller** [NEU-DSG/toolkit_requests#18]
@colleencurtis - do you want me to make the arader site title and navigation in two separate rows?
also wasn't sure if you wanted to hide the page title on the homepage?
Let me know and I can change it.

**Comment by colleencurtis** [comment]
Yes, both would be great.

**Comment by elizoller** [comment]
Ok will do. Let me know if there is anything else you'd like to change that isn't part of the "customize" page.

**Comment by elizoller** [comment]
It is updated. Let me know what you think. Thanks

**Comment by colleencurtis** [comment]
Title & navigation look great!

**Comment by elizoller** [comment]
OK let me know if there is anything else
