### ISSUE TITLE
Dropdown Menu Not Aligned

### ISSUE THREAD

**Issue by colleencurtis** [NEU-DSG/toolkit_requests#19]
The dropdown sections within the main menu are not aligned- preferably everything should be flush left, or otherwise consistent. The menu should reflect the page hierarchy: under exhibits, 'An age of Exploration' and 'Cartography Across the Centuries' should be equally aligned; all three subsections of each of those should be aligned; under about, the 3 pages should also be aligned. 

Not sure if this is a bug (since it's a new occurrence)- if not, can we add a menu alignment function on the customization menu? 
http://arader.library.northeastern.edu/

<img width="1242" alt="mainmenu-align" src="https://cloud.githubusercontent.com/assets/15789920/11601377/bec49d6c-9aa0-11e5-8a4e-cda5a47a3097.png">

**Comment by elizoller** [comment]
That would be a bug from the new changes I just made. Thanks for pointing it out.

**Comment by elizoller** [comment]
Fixed
