### ISSUE TITLE
Caption Alignment

### ISSUE THREAD

**Issue by colleencurtis** [NEU-DSG/toolkit_requests#20]
Can we add an option to align captions to the edges of the image (ie, flush left but spanning only image width)? Currently, captions feel separate from images, especially on home page gallery slider:
http://arader.library.northeastern.edu/

![captions-should-align-to-image](https://cloud.githubusercontent.com/assets/15789920/11638167/6bbfa184-9cf3-11e5-8693-b4d59b79fced.png)

**Comment by elizoller** [comment]
When the gallery goes to the next slide, would you want the caption to align to the start of that image so that the caption would change positions based on the width of the image?

**Comment by colleencurtis** [comment]
Yes

**Comment by colleencurtis** [comment]
Alternatively, an option within gallery slider to place the caption over the image on hover might work

**Comment by elizoller** [comment]
fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/ca988c31d7b8b3a7958bb780d3cbbe860702058d
