### ISSUE TITLE
Fauna collection from DRS not on toolkit

### ISSUE THREAD

**Issue by colleencurtis** [NEU-DSG/toolkit_requests#21]
Though we include broad categories of collections (maps and flora) on the toolkit, 'fauna' does not appear. We have all of its subsections (Audubon Prints, Marine Life Prints, and Avian Life Prints), but not Fauna itself. This affects both collections and browse pages. 
http://arader.library.northeastern.edu/collections/

![missing-fauna-collection](https://cloud.githubusercontent.com/assets/15789920/11638257/fac78db0-9cf3-11e5-8c8e-ba01dcd0850d.png)

**Comment by elizoller** [comment]
Fauna is on page 2

**Comment by colleencurtis** [comment]
Oops, glad it's there!
