### ISSUE TITLE
Collections dissapeared

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#23]
Collections on the Arader page disappeared. http://arader.library.northeastern.edu/collections/

![screenshot 2015-12-14 at 11 27 00 am](https://cloud.githubusercontent.com/assets/13038927/11786637/a00db6da-a255-11e5-997a-3f730d5cc211.png)

Checked A Proud Past and that was working.

**Comment by ablevesque** [comment]
Browse is also gone. 
![screenshot 2015-12-14 at 11 36 20 am](https://cloud.githubusercontent.com/assets/13038927/11786870/f85506f8-a256-11e5-99de-469808ff6f79.png)

**Comment by elizoller** [comment]
Looking into it. Just on Arader - can't replicate on any of the other sites. 
All of the sites have the same versions of wordpress, plugins, and themes (which are up to date). 
As far as I can tell it works for logged in users but not anonymous users.

**Comment by elizoller** [comment]
This seems to be working now. Not really even sure what I did to fix it if anything.

**Comment by ablevesque** [comment]
Aaand it's gone again. Still returning the same blank page with no error message on both search and browse. Still only on Arader.

**Comment by ablevesque** [comment]
On refresh, managed to get an error message in collections: 
![screenshot 2015-12-15 at 11 30 01 am](https://cloud.githubusercontent.com/assets/13038927/11816611/40055eee-a31f-11e5-99d9-57620db9c2dd.png)

**Comment by ablevesque** [comment]
Same error now showing up on browse.

**Comment by elizoller** [comment]
Ah ok.
There is an error message now. I'm looking into it. Browse and Collections are the same functions so it would make sense if one was broken that the other would be.

**Comment by elizoller** [comment]
I think it was a caching issue and is resolved now. Let me know if you are still experiencing the issue.
