### ISSUE TITLE
Caption Text Different Sizes

### ISSUE THREAD

**Issue by colleencurtis** [NEU-DSG/toolkit_requests#24]
Recently noticed that the text on image captions appears in different sizes for different widgets (single image is smaller). Not necessarily a huge issue, but as we use multiple widgets per page it would look nice to have a consistent size for all caption text (preferably the larger size that appears on gallery sliders). Currently affects 2 pages (links below); the rest have the larger size. 

http://arader.library.northeastern.edu/exhibits/mapmaking-across-the-centuries/
http://arader.library.northeastern.edu/exhibits/mapmaking-across-the-centuries/the-dutch-golden-age/

![textsize-mapmaking](https://cloud.githubusercontent.com/assets/15789920/11790971/9f54156a-a26c-11e5-932a-a9bb24ff384e.png)
![textsize-dutchgoldenage](https://cloud.githubusercontent.com/assets/15789920/11790972/a220b118-a26c-11e5-9a86-07d1b803156a.png)

**Comment by elizoller** [comment]
Makes sense.

**Comment by elizoller** [comment]
Fixed and deployed to Arader.
