### ISSUE TITLE
Sub-nav current location indication

### ISSUE THREAD

**Issue by AmandaRust** [NEU-DSG/toolkit_requests#25]
When on a page that is part of the sub-navigation, is it possible to have some sort of visual indication of where you are in the hierarchy? For example, this page is called "A Closer Look", 3rd from the bottom in the right-hand sub nav. There's no indication in the sub-nav of the fact that you're on "A Closer Look"..
![image](https://cloud.githubusercontent.com/assets/10200332/11936443/e9c40df2-a7db-11e5-8d2f-7fe63567516e.png)

By contrast, on the lib website your current location in the hierarchy is indicated on the left-hand nav; see the Scholarly Communication page where the menu item is red and underlined to the left: 

![image](https://cloud.githubusercontent.com/assets/10200332/11936463/09ca177c-a7dc-11e5-84a2-7e5e6d992749.png)

**Comment by elizoller** [comment]
I have changed it so it inherits the link accent color. https://github.com/NEU-Libraries/drs-toolkit-wp-theme/commit/a0040a64400454d33b71a92719a553dda35d1dda
