### ISSUE TITLE
Breadcrumbs accuracy

### ISSUE THREAD

**Issue by AmandaRust** [NEU-DSG/toolkit_requests#26]
This one may be user error, but I think that the breadcrumbs for "A Closer Look" should read: Home / Mapmaking Across the Centuries / A Closer Look. However, it only reads Home / A Closer Look. The URL shows we're correctly in the Mapmaking Across the Centuries directory, and the page has the proper "Mapmaking Across the Centuries" parent on the backend:

![image](https://cloud.githubusercontent.com/assets/10200332/11936509/5b2db966-a7dc-11e5-9755-83ddf977c162.png)

![image](https://cloud.githubusercontent.com/assets/10200332/11936520/67ca808c-a7dc-11e5-84e2-fa0144423c78.png)

**Comment by elizoller** [comment]
fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-theme/commit/1c6f708231af69f21e1b77d6137e4cf7bf83899f

**Comment by elizoller** [comment]
fixed with NEU-Libraries/drs-toolkit-wp-theme@d9550f5
Went with an alternate solution. The breadcrumbs will be built based on the nesting of the page in the wp-admin pages screen instead of using menu hierarchy because it is not possible to retrieve the menus from the sidebar.
