### ISSUE TITLE
Thumbnail for collections in browse

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#28]
Need a placeholder thumbnail for collections with no thumbnail on the browse page with sets.

![screenshot 2016-02-09 at 1 19 31 pm](https://cloud.githubusercontent.com/assets/13038927/12926129/edd3184a-cf2f-11e5-8a9f-b86498a25991.png)

**Comment by elizoller** [comment]
fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/297c109079ae62d90bb534ba0ffdb6e273fb5093
