### ISSUE TITLE
No thumbnails or DRS images in IE

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#29]
Sadow's site has nothing for images in IE except for media library items, even on item pages.
![image](https://cloud.githubusercontent.com/assets/13038927/13088417/2eb5389a-d4ba-11e5-9939-1da6bbe9457a.png)
![image](https://cloud.githubusercontent.com/assets/13038927/13088439/3c7fec04-d4ba-11e5-8686-ebcddd9a226e.png)

**Comment by ablevesque** [comment]
Works on the newest version of IE. David said he thinks it's an Ajax problem.

**Comment by elizoller** [comment]
what version of IE were you on before? and david is probably right hah ie + ajax = :boom:

**Comment by elizoller** [comment]
actually the item level page doesn't even use ajax anymore. what version of windows and IE are you running when you get the issue? i can't replicate in browser stack.

**Comment by ablevesque** [comment]
It's IE 10. More/possibly related: When you try to download a pdf from https://repository.library.northeastern.edu/downloads/neu:379124 this error shows:
![image](https://cloud.githubusercontent.com/assets/13038927/13503165/16da13d8-e13c-11e5-86de-0707619c1ad1.png)

**Comment by ablevesque** [comment]
Apparently Sadow is having more issues: more information to come.
