### ISSUE TITLE
Page number border for multipage rotating images

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#30]
The border at the bottom of the multipage rotating images is rather tall, especially for smaller items:

<img width="1213" alt="2016-02-25_1003" src="https://cloud.githubusercontent.com/assets/4663073/13323461/928472fc-dba7-11e5-9612-104605294d27.png">

For some, it covers more than half the image. Is this a setting the Toolkit user can change, or a default that we can change to make a bit smaller?

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-theme/commit/dcc173dbad75663e91a92c9e6dc9576ada0afc64

**Comment by sarahjeansweeney** [comment]
This looks much better. Thanks!
