### ISSUE TITLE
Making the "Site Tagline" click-able

### ISSUE THREAD

**Issue by gregjp48** [NEU-DSG/toolkit_requests#31]
Stephen Sadow has requested that his site title be multilingual. In order to separate the two, I have put the Spanish text in the "Site Title" and the English text in the "Site Tagline" when customizing the Wordpress site. Could you possibly make the Tagline clickable such that it also leads to the site's homepage? Otherwise, do you have suggestions for a cleaner solution?

Additionally, a horizontal rule between the two might be nice, but it isn't wholly necessary since the two texts are styled differently.

**Comment by elizoller** [comment]
Done.
