### ISSUE TITLE
Make anthology clickable on single item page

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#32]
Sadow wants the thumbnail to be clickable for Literatura judía latinoamericana contemporánea : una antología to let him open the PDF without having to scroll down to the button.

http://latinjewisharts.northeastern.edu/item/neu:379122

**Comment by elizoller** [comment]
@sarahjeansweeney  fixed this for this record by adding the issuu link in the mods record

**Comment by elizoller** [comment]
Fixed css to hide extra issuu links

**Comment by sarahjeansweeney** [comment]
:+1:
