### ISSUE TITLE
Arader site collections

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#33]
Ethan just reported this to me:
There are items and collections displaying on the Arader "Collections" page: http://arader.library.northeastern.edu/collections

<img width="761" alt="2016-03-04_1637" src="https://cloud.githubusercontent.com/assets/4663073/13540965/821ace58-e227-11e5-84a3-e3a330edd76d.png">

And when you click any of the collections, it just loops you back to the same result set, though with left facets:

<img width="1010" alt="2016-03-04_1638" src="https://cloud.githubusercontent.com/assets/4663073/13540969/87c05940-e227-11e5-9da7-a7c90ef482a7.png">

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/e9c12db07cadfb34a40c32644d59507ea23254d9
I broke it yesterday but its fixed now.

**Comment by sarahjeansweeney** [comment]
Thanks!
