### ISSUE TITLE
Audio thumbnails overlapping footer

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#34]
Audio thumbnails are glitching and overlapping the footer and each other when using page builder.

dmcstudios.library.northeastern.edu/audio

![image](https://cloud.githubusercontent.com/assets/13038927/14184420/1eeee6f8-f743-11e5-8a21-9f951df442eb.png)

**Comment by ablevesque** [comment]
This error seems browser and device agnostic - happened on Macs and also on my iPad

**Comment by elizoller** [comment]
I can't replicate on any device, browser, or simulator in my possession. Will chat about in meeting.

**Comment by ablevesque** [comment]
They're actively editing the page right now, but I have a hunch it was because there was a blank row.

**Comment by elizoller** [comment]
Closing this because I'm 99% it was the blank row causing this issue but feel free to reopen if the problem persists.
