### ISSUE TITLE
Video/Media Player Issue w/ Multiple Playlists per page

### ISSUE THREAD

**Issue by decampda** [NEU-DSG/toolkit_requests#35]
In our meeting with Thomas Bary from the DMC studios, we were trying to add single media playlists for each of the videos in it's own content blocks. Instead of displaying "The Bee Charmer" in one content row and "All I Have to Give" in the following one, the page grabbed "All I Have to Give" instead of "The Bee Charmer" and only inserted an image of "All I Have to Give" where it's video playlist is supposed to be. See below for the result (also available to see at http://dmcstudios.library.northeastern.edu/video). 

<img width="990" alt="dmcvideo" src="https://cloud.githubusercontent.com/assets/4481739/14185682/f82e03a4-f748-11e5-81af-be20e5cb25b2.png">

**Comment by elizoller** [comment]
Two options for doing this:

1.  Use the media playlist - it is fixed to allow multiple playlists on one page  ( https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/ea72ce12ff20a18ac2b9ee61bbc17547d7c3f4cb )

2. Use the single item embed - damon added the functionality for using the streaming video - is it an option in the shortcode settings that says "Display Audio/Video Stream"
<img width="363" alt="screen shot 2016-03-31 at 3 21 51 pm" src="https://cloud.githubusercontent.com/assets/5439169/14188105/569c3bee-f754-11e5-8e35-c04af6e6e600.png">
