### ISSUE TITLE
Text overlapping images on Arader.

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#36]
Jenny Sartori reported text and image overlap on one of the Arader pages. http://arader.library.northeastern.edu/exhibits/an-age-of-exploration/early-colonial-cartography
She's using Firefox. 

![arader](https://cloud.githubusercontent.com/assets/13038927/14890485/d8749ad4-0d30-11e6-9a99-6749968eeb1f.png)

**Comment by elizoller** [comment]
Should be fixed now. 28e16db695eb9de59d7b0fe2ad45f0a3479384a8 7d5e2b67484d784e9a5561f3353cf66c78489958 395a53761f6e43c886f507dfb6466bf0b7fb281f 7d069c20aa0e9b6515a24a068926d70592f641a2
