### ISSUE TITLE
Tile Gallery Formatting Bug

### ISSUE THREAD

**Issue by colleencurtis** [NEU-DSG/toolkit_requests#4]
Pinterest style gallery on 'test draft' has captions placed on top of text (a separate widget). 
Occured on laptop/Firefox
http://arader.library.northeastern.edu/testdraft/

![tilegallerycaptions](https://cloud.githubusercontent.com/assets/15789920/11075053/248c8bde-87c1-11e5-9d6f-8b773fc04d30.png)

**Comment by elizoller** [comment]
I think this is related to https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/issues/54

**Comment by elizoller** [comment]
fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/387e2760fd31a63d1547479a074bbf23dc7eba06
