### ISSUE TITLE
Latin Jewish Artists site subpages are down

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#40]
The Latin Jewish Artists and Writers homepage is up, but none of the other pages are:

http://latinjewisharts.northeastern.edu/about

![2016-05-11_1615](https://cloud.githubusercontent.com/assets/4663073/15194963/a0c25aaa-1793-11e6-828c-9cc52af392c7.png)

**Comment by elizoller** [comment]
I am going to work with karl on this.
This site has been under attack recently and I think some of the protection may have gone overboard.

**Comment by elizoller** [comment]
Karl just toggled the security plugin off and back on again. Because the site had been hit so much and the plugin has been working so hard to block IPs, we think it may have just gone into a fritzy state. The site is back up.

**Comment by sarahjeansweeney** [comment]
Great, thanks!
