### ISSUE TITLE
Latin Jewish Arts is down

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#43]
Front page loads, every other page gives an error.

![screenshot 2016-05-27 at 11 22 00 am](https://cloud.githubusercontent.com/assets/13038927/15612602/7f1beca6-23fd-11e6-8e94-d10b9ffc5cde.png)
![screenshot 2016-05-27 at 11 21 55 am](https://cloud.githubusercontent.com/assets/13038927/15612607/843691d2-23fd-11e6-86cb-c7e0d8f7b21a.png)

**Comment by elizoller** [comment]
Same issue as before. Toggling on and off the security plugin fixed it. Going to talk to Karl and see if there is a way to prevent this from happening.
