### ISSUE TITLE
No visual widget on page builder on Thoreau

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#44]
![screenshot 2016-06-02 at 11 36 16 am](https://cloud.githubusercontent.com/assets/13038927/15750984/6504c050-28b6-11e6-8c02-e21faa613359.png)

thoreaudrawings.neu.edu doesn't have the visual editor in page builder that lets us use DRS items.

**Comment by elizoller** [comment]
Sorry forgot to install a plugin.
Fixed now.
