### ISSUE TITLE
Add DRS item shows up as blank in Safari

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#45]
Attempting to add shortcodes shows up as a blank box in Safari on liblab.neu.edu/drstest. Works in Chrome. 

![safari-adddrsitem](https://cloud.githubusercontent.com/assets/13038927/15763188/28425a26-28f0-11e6-898f-2b68ea476ca4.png)

**Comment by elizoller** [comment]
This is fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/e4c114cab2560c7e802728ca4eac6dea7a90752e but had not been deployed to liblab test site. It is now.
