### ISSUE TITLE
Latin Jewish Arts giving a server error.

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#46]
Greg is having issues getting into the admin side of Latin Jewish Arts - it says he's been forbidden from permission to access that page. I can't replicate the error on my computer and I can access the admin panel just fine. Dave, however, is getting the same error. Appears to be browser agnostic, as one is on Chrome and the other is on Safari.

URL giving them the issue is latinjewisharts.neu.edu/wp-login.php

![lja-admin](https://cloud.githubusercontent.com/assets/13038927/15763355/452bb938-28f1-11e6-9acf-98f96628c87f.png)

**Comment by elizoller** [comment]
Are they off campus and you on campus by any chance?

**Comment by ablevesque** [comment]
No, all on campus. Only difference I can think of is Mac vs. my chromebook.

**Comment by elizoller** [comment]
Hmm ok I will have to talk to Karl about it tomorrow

**Comment by ablevesque** [comment]
If it helps at all, I'm now also receiving this error, at least while I'm off-campus.

**Comment by elizoller** [comment]
Confirmed with Karl, there is still a restriction for off campus that requires you to use the VPN in order to access the admin panel. He is going to remove that today since we have not been hit in a few days. I think this resolves the issue with his work on the .htaccess file the other day.
