### ISSUE TITLE
Feature requested: embedded page turning in exhibits

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#47]
Spectrum was asking if it's possible to make it so issuu items can be turnable when they're embedded in an exhibit instead of just on their item page. 

Not sure if it's feasible, just something they were interested in.

**Comment by elizoller** [comment]
Through which shortcode? The single item?

**Comment by ablevesque** [comment]
I think so, yeah.

**Comment by elizoller** [comment]
The only issue I see with this is that we currently use the images as links back to the full item. This wouldn't do that because it would link to issue. Should I add a text link at the bottom that links to the full item?

**Comment by elizoller** [comment]
I deployed this but I'm not sure its having the desired affect because of Sadow's site - 
http://latinjewisharts.northeastern.edu/works
If you don't want it on all the time, we can make it a configuration option.

**Comment by elizoller** [comment]
Going to add this as a config option
