### ISSUE TITLE
Base layer not showing up on Thoreau site

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#48]
![screenshot 2016-06-13 at 4 07 14 pm](https://cloud.githubusercontent.com/assets/13038927/16021532/3abd66a2-3181-11e6-877e-9fc801ace8d3.png)

URL is: http://thoreaudrawings.northeastern.edu/19-2/

Maps isn't showing a base layer, even when there's nothing on the page but the map.

**Comment by elizoller** [comment]
Without any items the js won't set up a base area for the map

**Comment by paramajmera** [comment]
Hey Eli! I also tried making a map today and included items, but the map layer is still not showing up 

![screen shot 2016-06-26 at 4 35 05 pm](https://cloud.githubusercontent.com/assets/15788058/16364713/f938eb6c-3bbb-11e6-90d6-fcc89f535abb.png)

**Comment by elizoller** [comment]
I am still looking into this. I've copied the shortcode and put in another site (like liblab or my local install and they work just fine). Then I tried copying a shortcode from another site that works and it does not work in Thoreau so it something with that install specifically. Still looking into it.

**Comment by elizoller** [comment]
Finally got this sorted with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/9ea9ba628fa0dbab63082260198bc027658cf425 and https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/ddd52904bba7fe961de80378d365696c752aa87f
