### ISSUE TITLE
Timeline Bug

### ISSUE THREAD

**Issue by paramajmera** [NEU-DSG/toolkit_requests#50]
The timeline feature is including colors that I didn't select in the legend description. I only wanted the red and the green categories but the timeline has also put stuff in the grey/white category. Furthermore, when building this timeline I also specified that the item named "Woodchuck Tracks March 16, 1855" should be in the red category, but somehow its always being included in the green category. 

![screen shot 2016-06-26 at 4 36 07 pm](https://cloud.githubusercontent.com/assets/15788058/16364803/ac58ae7a-3bbd-11e6-9fee-c696f21420c9.png)

**Comment by elizoller** [comment]
I have a fix for this already in develop. I'll merge it in sometime this week.

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/pull/111
