### ISSUE TITLE
No validation on single item/weird error

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#51]
![screenshot 2016-06-29 at 12 25 10 pm](https://cloud.githubusercontent.com/assets/13038927/16460524/bae4d2f4-3df5-11e6-82b1-23c9bdd39b9b.png)

Just poking the site for the new interface. I think this has to do with it trying to validate but somehow not doing it - it looks like it's looking for the DPLA item in the DRS search box. I can tick as many boxes as I want, but I assume actually trying to do anything would break it.

**Comment by elizoller** [comment]
What steps did you go through to have this happen?

**Comment by ablevesque** [comment]
If I went from selecting a DPLA item to the DRS items tab, that was when this showed up.

**Comment by ablevesque** [comment]
Okay, I played around a bit. On the DRS it only lets you check one box. On the DPLA tab it lets you pick more than one but yells at you if you try to actually insert the shortcode. However, if you select anything in the DPLA tab, even if you go and unselect it, the error above happens where it tries to search what appears to be the DPLA item's ID number - if I switch from DPLA to DRS and back it even carries over the search onto the DPLA tab.

**Comment by elizoller** [comment]
Single item should only let you select one item.
I just pushed up a fix that removes the search string when you change tabs so that you wont be doing the dpla search on the drs page.

**Comment by ablevesque** [comment]
It might be because the change isn't pushed to liblab yet, but it's also happening on the gallery slider: 
![screenshot 2016-06-29 at 12 52 39 pm](https://cloud.githubusercontent.com/assets/13038927/16461022/72a6bf18-3df8-11e6-9482-c213f6b88533.png)

(Picture being the name of the item I have selected on the DPLA tab.)

**Comment by ablevesque** [comment]
It also keeps doing it even if I delete the string from the search bar manually - it repopulates itself when I switch the tab.

**Comment by elizoller** [comment]
I'm working on it locally then I'll push it up to liblab.
