### ISSUE TITLE
Tile gallery in a single widget appears as one giant item

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#52]
Url is a draft page:  http://liblab.neu.edu/drstest/1633-2/

![screenshot 2016-06-29 at 12 27 15 pm](https://cloud.githubusercontent.com/assets/13038927/16460595/24bb72be-3df6-11e6-8de5-f3cce5432be5.png)

Items in a mixed (dpla, outside, and DRS) set appear as one giant item, with one piece of metadata showing for it - clicking brings you to that item's page whose metadata displayed. Still does it with just DRS items: 
![screenshot 2016-06-29 at 12 39 28 pm](https://cloud.githubusercontent.com/assets/13038927/16460682/8ced6bbc-3df6-11e6-8eab-5e9dcc24c3c4.png)

Problem resolves if a second row is added - I tried it with a second tile gallery below and it was fine.

**Comment by elizoller** [comment]
I think this is fixed also - can you verify or send me a link?

**Comment by ablevesque** [comment]
Verified, it now works!
