### ISSUE TITLE
DPLA items lead nowhere

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#53]
If I try to click DPLA items, it brings me to this: 

![screenshot 2016-06-29 at 12 41 02 pm](https://cloud.githubusercontent.com/assets/13038927/16460803/3c56cf76-3df7-11e6-9973-6c84cbec04ac.png)

URL is http://liblab.neu.edu/drstest/item/4c295d8a0dcfcf55d7cbb3310daf0fed/

**Comment by elizoller** [comment]
This should be fixed now.
