### ISSUE TITLE
DPLA text items have only the logo as their thumbnail

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#54]
URL is draft page: http://liblab.neu.edu/drstest/1633-2/

![screenshot 2016-06-29 at 12 30 36 pm](https://cloud.githubusercontent.com/assets/13038927/16460839/6c16ef8e-3df7-11e6-8eb9-f6d47da8d5b4.png)

Picture items seem to have a thumbnail - haven't tried any other media types.

**Comment by elizoller** [comment]
if DPLA does not provide a thumbnail then I've put in the DPLA logo - I can change it to that stock image icon that I've inserted into the back end search but either way, we have no reliable way of getting a thumbnail from the dpla if it isn't an image object.
