### ISSUE TITLE
Gallery slider shortcode is being displayed as a previous shortcode

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#55]
Even after saving the page, the old shortcode is what displays.

Url is : http://liblab.neu.edu/drstest/1633-2/

![screenshot 2016-06-29 at 12 57 12 pm](https://cloud.githubusercontent.com/assets/13038927/16461179/4e32829c-3df9-11e6-91af-a3bec50d089c.png)
![screenshot 2016-06-29 at 12 57 17 pm](https://cloud.githubusercontent.com/assets/13038927/16461182/53a2dcf4-3df9-11e6-84e3-fee9d5e23c23.png)

**Comment by ablevesque** [comment]
Wiping the whole page and rebuilding fixed it, but now items aren't displaying. 

![screenshot 2016-06-29 at 1 00 19 pm](https://cloud.githubusercontent.com/assets/13038927/16461229/84f3fb30-3df9-11e6-9cf8-e37330133a0a.png)

**Comment by ablevesque** [comment]
This affects both DRS and non-DRS items. DRS items appear to be clickable still, and so do outside items, but trying to click DPLA items makes the slider go backwards. Also, it's barely visible, but it appears there's some small bit of white text over the caption.

**Comment by elizoller** [comment]
I think this was just a caching issue.

**Comment by elizoller** [comment]
fixing styling with https://github.com/NEU-Libraries/drs-toolkit-wp-theme/commit/8fc54f12aae486712830135ea8fe0f3f526d9c64

The other part of this I'm fairly certain was a caching issue. If you experience it again, please reopen.
