### ISSUE TITLE
If there are two rows of gallery sliders, the second is not scrollable

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#56]
![screenshot 2016-06-29 at 1 04 20 pm](https://cloud.githubusercontent.com/assets/13038927/16461362/29c59222-3dfa-11e6-8566-52a537abd6f8.png)

URL  http://liblab.neu.edu/drstest/1633-2/ 

If I try to clock that bottom slider to see the next picture, it instead moves the top slider. The item is still clickable and brings me to the correct single item page.

**Comment by elizoller** [comment]
I can't replicate this now either. Can you verify or send me another link?

**Comment by elizoller** [comment]
I'm fairly certain this is fixed also. Please let me know if you are still experiencing it.
