### ISSUE TITLE
Two columns of gallery sliders show up as rows.

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#57]
This might be inherent to the page builder: If I try to make two gallery sliders sit side by side, they automatically become rows instead.

![screenshot 2016-06-29 at 1 07 27 pm](https://cloud.githubusercontent.com/assets/13038927/16461446/9a4e791e-3dfa-11e6-9261-5a8a88d0a920.png)
![screenshot 2016-06-29 at 1 07 35 pm](https://cloud.githubusercontent.com/assets/13038927/16461453/9efc6dea-3dfa-11e6-8bb9-e18026068d08.png)

**Comment by elizoller** [comment]
This works for me:
<img width="1267" alt="screen shot 2016-07-06 at 3 22 41 pm" src="https://cloud.githubusercontent.com/assets/5439169/16631516/8a7695d8-438d-11e6-85a1-ba89ae6e89fe.png">
Are you still experiencing this issue?

**Comment by elizoller** [comment]
I think this is resolved. Please let me know if you are still experiencing this issue and I will investigate further.
