### ISSUE TITLE
Sometimes the UI inserts shortcode without closing.

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#58]
![screenshot 2016-06-29 at 1 12 35 pm](https://cloud.githubusercontent.com/assets/13038927/16461586/39eb98a8-3dfb-11e6-9dff-8405b69f2f09.png)

I can't figure out what makes it do this, it's inconsistent. I can't tell if it's because it's a mix of DPLA and DRS items with no outside items, or because it's a tile gallery, or what.

Essentially I click it and it inserts the shortcode but only closes the UI if I click cancel. I added one shortcode like... 15 times before I realized it.

**Comment by elizoller** [comment]
I think this was an ordering issue, resolved in https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/f969d43dfcf21d2c6042e31f5d62e5499e020dd1 but do let me know if you are experiencing this again.
