### ISSUE TITLE
Metadata Captions Overlap Images

### ISSUE THREAD

**Issue by colleencurtis** [NEU-DSG/toolkit_requests#6]
When inserting media from DRS into a gallery slider, I include the title, author, and date of each piece. The text appears in a frosted box on top of the image, and blocks the bottom of the image. Do not want to block the images. In pinterest style/tile galleries, there is an option for text to appear only on hover, but I'd like the caption to appear for gallery sliders below the image, and not solely when hovered over. 

http://arader.library.northeastern.edu/exhibits/an-age-of-exploration/
![slider-textblock](https://cloud.githubusercontent.com/assets/15789920/11193360/484c6528-8c74-11e5-8c09-56e16654df7a.png)

mobile view:
![img_5129](https://cloud.githubusercontent.com/assets/15789920/11193434/9b6484d4-8c74-11e5-9c32-e7a04d024054.jpg)

**Comment by elizoller** [comment]
There is a setting option for this now. 
`caption-position="relative" ` (below image) vs `caption-position="absolute"` (over image)
<img width="289" alt="screen shot 2015-11-17 at 9 41 48 am" src="https://cloud.githubusercontent.com/assets/5439169/11214491/8ff49576-8d0f-11e5-9f20-375593c4ce02.png">
<img width="295" alt="screen shot 2015-11-17 at 9 41 52 am" src="https://cloud.githubusercontent.com/assets/5439169/11214492/93a62d42-8d0f-11e5-8f32-0e4255962301.png">
