### ISSUE TITLE
Feature request: "This item appears on..."

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#60]
Ben brought up a good point. It might be useful to have the single item pages scrape the site and display the URLs of where an item appears (maybe making it pretty by having the display text be the page names.) So for example, if an item is in 3 exhibits, having it's single item page display "See this item:" and a list of exhibit links.

**Comment by elizoller** [comment]
Fixed with 0c7623ba4401466a88d59a5e660f8ecdfe84b71d through de4ec3997b7c4c38258d1b8686408d8931af9bd8
