### ISSUE TITLE
No metadata on single items

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#61]
![screenshot 2016-08-11 at 4 15 46 pm](https://cloud.githubusercontent.com/assets/13038927/17603431/0889c126-5fdf-11e6-86e2-fd7de247d112.png)

Single items no longer have any metadata options, and trying to edit shortcodes with single items that used to have metadata no longer have it. On dmcstudios.northeastern.edu, and replicated on liblab.

**Comment by elizoller** [comment]
Should be fixed
