### ISSUE TITLE
Not all URLs are hyperlinked on item pages

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#62]
URLs stored in some MODS fields are displaying as links, while others are not: http://ecda.northeastern.edu/item/neu:m040gb50q/

![ecdalinks](https://cloud.githubusercontent.com/assets/4663073/18587159/7c503af6-7bee-11e6-8f27-47e10edd4c5c.png)

All links stored in the item page metadata should be hyperlinked.

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/a8408abb269caa76be12bd6a560de79dc08425e5
