### ISSUE TITLE
Items on map can't be clicked to go to their single item page

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#64]
instead directs to /map/item/PID instead of just /item/PID.

![screenshot 2016-09-22 at 2 09 18 pm](https://cloud.githubusercontent.com/assets/13038927/18760239/3e976da8-80ce-11e6-9d1a-e1d66c49a879.png)
![screenshot 2016-09-22 at 2 09 28 pm](https://cloud.githubusercontent.com/assets/13038927/18760246/4550e4b2-80ce-11e6-8426-dd731fe15129.png)

**Comment by elizoller** [comment]
closed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/a4155abd94c11a8972c4de32adbdb16ac2022cf3
