### ISSUE TITLE
"Item Appears In" displaying raw data

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#65]
Similar to #41 and https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/issues/40, the new "Item Appears In" box is displaying more than just the page content:

<img width="994" alt="2016-09-23_0956" src="https://cloud.githubusercontent.com/assets/4663073/18788411/bdbe68ec-8174-11e6-8b35-1f24bae18af9.png">

**Comment by elizoller** [comment]
Ugh. I really need to fix that bug.

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-theme/commit/3719a5de0afcb02e3a4ca6fe8bcd262c788ac91d
