### ISSUE TITLE
"Item appears in" text display

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#66]
The "Item appears in" text box looks like it's displaying all text in the exhibit, including headings and paragraph text squished together:

![2016-09-27_0909](https://cloud.githubusercontent.com/assets/4663073/18875095/4ef78274-8492-11e6-8acc-4db307ddd0d6.png)

There's a mix of headings and text on the ECDA page above. I also think it doesn't have a page title.

![2016-09-27_0911](https://cloud.githubusercontent.com/assets/4663073/18875126/67a3687e-8492-11e6-98ca-65c3686d2596.png)

The Catskill example looks better because of the page title, but the "About" heading still runs together with the body text.

I can't think of an easy way to improve this, so I'm open to suggestions. I suppose only displaying body or paragraph text in the box could be one solution, if that's possible.

**Comment by elizoller** [comment]
I can remove the text of the shortcodes if you like so it would only display the text entered by the user. 
Can you send me the link for the ECDA one? Might be a CSS issue for the title not displaying.

**Comment by sarahjeansweeney** [comment]
That sounds like a good idea. Here's the ECDA link: http://ecda.northeastern.edu/item/neu:m040g715h/

**Comment by elizoller** [comment]
Yeah, issue with ECDA is custom CSS hides it. I'll modify so it isn't hidden.

**Comment by elizoller** [comment]
Custom CSS fixed.
