### ISSUE TITLE
"Request Entity Too Large" error saving exhibit page

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#68]
Kaley is building a rather large Toolkit page that contains a lot of text and she's testing out a few different page layouts in order to replicate this page:http://www.brown.edu/Research/Catskills_Institute/hotelsbungalows.shtml . She ran into an error when saving this particular page:  http://catskillsinstitute.northeastern.edu/exhibits/hotels-and-bungalows/hotels-and-bungalows-draft/ (page title: "Hotels and Bungalows (draft)")

![screen shot 2016-09-29 at 3 19 14 pm](https://cloud.githubusercontent.com/assets/4663073/18969863/fc295d5c-865c-11e6-949a-a1d7b96fd517.png)

There are a lot of slider galleries on this page, but she didn't run into the error adding new galleries, just more text. 

I was able to replicate by adding a new row to that page and a visual editor with a lot of text (~5000 words). This is certainly a lot of text, and we'll probably rethink the design of this page to make sure it isn't so text-heavy. I'm not sure if this is an issue to be fixed, per se, but there's clearly a limit on the size of pages, so we should find out what that is for future reference.

**Comment by elizoller** [comment]
Going to look into proposed solutions here: https://wordpress.org/support/topic/413-request-entity-too-large-9/

**Comment by elizoller** [comment]
Are you able to replicate this still?

**Comment by sarahjeansweeney** [comment]
Yes, I just copied ~6000 words into a visual editor on this page: http://catskillsinstitute.northeastern.edu/?page_id=146&preview=true

Ran into the same error.

**Comment by elizoller** [comment]
Ok, I'll up the max request and post sizes in the PHP config to hopefully better accommodate posts of this size. Karl has put in a request to double the CPU cores and RAM on the machine so I'm going to wait until those happen before implementing this.

**Comment by sarahjeansweeney** [comment]
👍

**Comment by elizoller** [comment]
This should be resolved with WP_MEMORY_LIMIT increase
