### ISSUE TITLE
Catskills Site 500 Error

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#71]
Kaley reported that she started seeing an error page while working on the Catskills site:

![2016-10-31_0920](https://cloud.githubusercontent.com/assets/4663073/19855584/c5fca1dc-9f4b-11e6-93cf-df2744ac103d.png)

Here's her description of the error:

> It doesn't happen consistently. Sometimes it has a Reload button right on the screen with the message and sometimes it doesn't. Sometimes it's when I'm trying to preview a page, which isn't a big deal, but others it's when I click Save Draft. And then when I reload this error page, it brings me to the posts page (which has nothing) and when I return to the page I was working on, what I was trying to save hasn't saved. 

I was able to replicate by going to http://catskillsinstitute.northeastern.edu/wp-admin/ (which is where the above screenshot comes from).
Reloading the page worked and I was able to login and browse around without seeing the message again.

**Comment by elizoller** [comment]
Are you able to replicate this anymore? I made a few adjustments

**Comment by sarahjeansweeney** [comment]
I can't. Seems much better.

**Comment by sarahjeansweeney** [comment]
Kaley and I both ran into this again today.

**Comment by sarahjeansweeney** [comment]
Still running into this error:

> catskillsinstitute.northeastern.edu is currently unable to handle this request.

<img width="1280" alt="2017-01-12_1307" src="https://cloud.githubusercontent.com/assets/4663073/21902007/3172f6e0-d8c8-11e6-9180-6ca071df9ed0.png">

It's still intermittent, but I've noticed it happening more often.

**Comment by elizoller** [comment]
Trying to edit or trying to view?

**Comment by sarahjeansweeney** [comment]
Just trying to view the page, not logged in.

**Comment by elizoller** [comment]
did you try a hard refresh?

**Comment by sarahjeansweeney** [comment]
I did not, but I'll try next time I see it.

**Comment by elizoller** [comment]
Hmm ok I'll look into it more

**Comment by elizoller** [comment]
I increased the max execution time and memory limit settings for PHP but this is definitely something to keep an eye on because I am not seeing anything illuminating in the logs.

**Comment by sarahjeansweeney** [comment]
Okay, thanks. I just visited the site and ran into the same error, though a hard refresh worked to bring up the site.

**Comment by elizoller** [comment]
I took another look at this as it was still bothering me - turns out I had defined the increase in WP_MEMORY_LIMIT in the wrong order so it was not taking affect. This should be fixed now. Please do let me know if you hit the 500 page again.
