### ISSUE TITLE
Image changing size in gallery slider

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#72]
Kaley reported some unexpected behavior with some of the gallery sliders on this page:  http://catskillsinstitute.northeastern.edu/exhibits/hotels-and-bungalows/li-ro/

All the files in the gallery are (or should be) the same size, so when the images rotate the gallery stays about the same size. When you click through some of the galleries (Parksville, in particular), some of the images change size and don't fit in the gallery window. To replicate:

- Go to the Parksville slider gallery on the page linked to above
- Click through from the first to the second file (images one and two are the same size)
- Click through from the second file to the third file
- On the click through to the third file the second file gets larger and stays that way, with the left and right navigation arrows now inside the image:

![2016-11-18_1223](https://cloud.githubusercontent.com/assets/4663073/20439550/04d6774c-ad8a-11e6-8802-dea559ccdc28.png)

Here's another example of a gallery with this behavior: 
"White Lake" http://catskillsinstitute.northeastern.edu/exhibits/hotels-and-bungalows/sa-yu/

Here's a video of this behavior in action: https://www.dropbox.com/s/ub205gyy37cm9r4/catskillsgallery.mov?dl=0

**Comment by elizoller** [comment]
I think I've got this sorted better. Can you check again on this page? You may need to do a hard refresh to get the updated JS/CSS for this to work.
Thanks!

**Comment by sarahjeansweeney** [comment]
We just tried it out and it looks good. Thanks!

**Comment by elizoller** [comment]
fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/1bc96209c563a9110b51666f2ee217c2eb9cfe16
