### ISSUE TITLE
Visual Editor Text Appears in all White Sometimes

### ISSUE THREAD

**Issue by paramajmera** [NEU-DSG/toolkit_requests#76]
Text bar doesn't show up and the text appears in white

![screen shot 2017-03-30 at 9 46 36 am 2](https://cloud.githubusercontent.com/assets/15788058/24519074/f48edfd4-1551-11e7-81e7-3856cb841eaa.png)

**Comment by sarahjeansweeney** [comment]
This is still happening or happening again. Reported by Kaley:

> I'm encountering a problem with adding widgets to pages in the documentation website that I think I've seen before... When I create new Visual Editor widgets and am looking at them in the visual section, they don't have the text editing bar at the top and all the text displays as white so I have to highlight it to see it. Widgets that already existed on this page don't have this problem and it doesn't happen when I duplicate existing widgets... The screenshots below show the difference between the widget that someone else made and the one I added.

Empty visual editor (made by Kaley):
![new widget](https://user-images.githubusercontent.com/4663073/31513530-9cc79eda-af5c-11e7-9f8c-880d56bece38.png)

Visual editor working as expected (made by previous user):
![old widget](https://user-images.githubusercontent.com/4663073/31513541-a6855638-af5c-11e7-9a01-1b7cea6cd733.png)

**Comment by decampda** [comment]
This came up in Victoria's class on 9/20. I was using google chrome on the classroom's desktop (was doing a live demonstration, so didn't have the chance to get the version number). I was entering a shortcode for the pinterest-style gallery using items from DRS, DPLA, and the local media library. When I clicked "insert short code" the pop up visual editor's text was all white and the shortcode was not able to be edited. However, when I published/updated the page, returned to the main admin dashboard, then navigated back to the page/shortcode it was displaying as intended (black text and able to be edited).

**Comment by patrickmj** [comment]
This is tricky since it looks like it is inconsistent and hard to reproduce. Quick research makes it look like it's a problem with a javascript file not loading properly, which makes it make sense that reloading the page fixes it. So, at least until we have more data to go on, I'll put this back as closed.
