### ISSUE TITLE
Images from DPLA are only displaying as thumbnails

### ISSUE THREAD

**Issue by paramajmera** [NEU-DSG/toolkit_requests#78]
Images from the DPLA are only displaying as thumbnails, even if DPLA contains good quality images. Changing the image size in page-builder does not appear to have any effect. Please see the following link for an example -  http://toolkittraining.dsg.northeastern.edu/param-test-2/.

**Comment by elizoller** [comment]
The DPLA API only provides one image for each item which is typically of thumbnail size.
