### ISSUE TITLE
Sidebar Panel

### ISSUE THREAD

**Issue by colleencurtis** [NEU-DSG/toolkit_requests#8]
Is there a way to add a background color for the sidebar?

Sidebars will be visible on all 'exhibit' pages within Picturing the World, example:
http://arader.library.northeastern.edu/exhibits/cartography-across-the-centuries/a-closer-look/
![a closer look](https://cloud.githubusercontent.com/assets/15789920/11286196/a0676dce-8ee1-11e5-8c28-72880fc74b8c.png)

**Comment by elizoller** [comment]
Added setting for sidebar background color under customize > colors > sidebar
( https://github.com/NEU-Libraries/drs-toolkit-wp-theme/commit/bbb61404c0f77c3c4f88677e0384c4a05734b6c4 )
