### ISSUE TITLE
Users unable to create passwords

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#80]
I've added both Sarah Connell and Elizabeth Dillon to the sandbox site for their training. However, no matter what password is entered (even the ones generated by WordPress) the site wouldn't allow sarah to create her password. URL is for the login link (from the account creation email) for toolkittraining.dsg.northeastern.edu

<img width="546" alt="screen shot 2017-05-15 at 11 41 10 am" src="https://cloud.githubusercontent.com/assets/13038927/26067035/cbbb3498-3966-11e7-9fd8-764f7ca6250c.png">
<img width="499" alt="screen shot 2017-05-15 at 11 41 25 am" src="https://cloud.githubusercontent.com/assets/13038927/26067034/cbb5332c-3966-11e7-816c-658fefb7b447.png">

**Comment by elizoller** [comment]
i just tried creating an account for myself on toolkittraining.dsg.northeastern.edu and i was able to set a password no problem. try resetting their passwords for them in the admin interface and then sending them that password. once they login with that password, they can change it to something else (in theory). let me know how it goes

**Comment by elizoller** [comment]
Any luck?

**Comment by ablevesque** [comment]
Seems like it started working with a reset password.
________________________________

**Comment by elizoller** [comment]
When had you created the users? If a user doesn't login without a certain amount of time, the initial password expires.

**Comment by ablevesque** [comment]
We're still having issues with this on the test site - Ping Sarah Payne and Param for more information

**Comment by sarahjeansweeney** [comment]
I just experienced this issue. Someone (Karl?) created an account for me here: http://ocr.northeastern.edu/

I received the notification at 2:01pm and tried setting my password around 2:40pm. I tried using a variation of a strong password I use for other toolkit sites, but got this message:

> Error: Due to site rules, a strong password is required. Please choose a new password that rates as Strong on the meter. The password has not been updated.

I tried a few passwords that meet the "strong" requirements (they were marked as "strong" by the meter), but none worked:

> Hint: The password should be at least twelve characters long. To make it stronger, use upper and lower case letters, numbers, and symbols like ! " ? $ % ^ & ).

**Comment by ablevesque** [comment]
Sarah,


Can you mention this to Karl? We've been having this problem non-stop with no solution in sight, and we have a training session Thursday.


Best,

Abbie

________________________________

**Comment by KarlYee** [comment]
I got in on the first try, using the auto generated pw.

**Comment by sarahjeansweeney** [comment]
Karl temporarily disabled the iThemes Security plugin, which allowed me to reset my password. This is not a permanent solution, but it's more practical than deleting and recreating users, or having admins reset passwords hoping that will work.

We left the security plugin in place, but in the future if a user reports this problem an admin (preferably Karl or Sarah) can disable the site's iThemes Security plugin temporarily while a user creates their password.

**Comment by KarlYee** [comment]
It was inconclusive. Initially Sarah could get in.  Then the iThemes security plugin was turned off.  Sarah, using an auto generated pw got in.   Next, the plugin was turned on again.  Sarah retested, again using an auto generated pw.  She got in!  

Next, I configured IThemes Security to only require strong pw for Admin account.  Sarah, now configured with "contributor" credentials, tried using an auto generated pw.  It worked!

**Comment by KarlYee** [comment]
For now on ocr.northeastern.edu,  iThemes Security plugin is configured to require strong pw for admin users only.

**Comment by KarlYee** [comment]
Did anyone have any password issues during today's training session?

**Comment by sarahjeansweeney** [comment]
I did not attend the session, but none were reported when we discussed the session with @ablevesque and Caroline later in the day.

**Comment by cklibanoff** [comment]
Sarah Payne is having this issue currently with the [Holocaust Awareness](http://holocaustawarenessarchives.northeastern.edu/) site. I've generated her a new password in the meantime.

**Comment by sarahjeansweeney** [comment]
Hillary Corbett just reported this issue on the CLMS site: http://clms.library.northeastern.edu/ 
Regenerating her password worked.

**Comment by sarahjeansweeney** [comment]
The Library Dean just encountered this issue in the What's New Podcast site: http://whatsnewpodcast.org/
