### ISSUE TITLE
SiteOrigin Button

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#81]
Jenni wants to add styled buttons to the [CLMS](http://clms.library.northeastern.edu/) site, similar to those on the [Catskills](http://catskillsinstitute.northeastern.edu/) site. I don't remember who created the buttons in Catskills, but they used the SiteOrigin Button widget, which works quite well.  I instructed Jenni to do the same in CLMS, but she received this message when trying to add it to a page:

![capture](https://cloud.githubusercontent.com/assets/4663073/26125954/d156bbf2-3a51-11e7-9580-964dd2c8719b.PNG)

To replicate:

- Navigate to http://clms.library.northeastern.edu/?page_id=19&preview=true (just my test page, can't do any harm)
- Click "Add widget" to add the SiteOrigin Button widget
- Edit the widget
- At this point you should see the message

Is this a special widget that needs to be installed? Or does SiteOrigin need to be updated in order for her to use the button widget?

**Comment by elizoller** [comment]
It's just another plugin which can be added no problem. I've installed it on the CLMS site.

**Comment by sarahjeansweeney** [comment]
Thanks!
