### ISSUE TITLE
Video behavior in playlist/single item exhibits

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#82]
Thomas reported that the wrong video was embedded on the DMC Studios Video page: http://dmcstudios.library.northeastern.edu/video

[Jelly Apple](http://dmcstudios.library.northeastern.edu/item/neu:cj82px08t) is the first exhibit on the page, embedded using the following shortcode:

[drstk_single id="neu:cj82px08t" image-size="4" display-video="true" display-issuu="true" align="center" float="none" caption-align="left" caption-position="below" zoom="on" zoom-position="1"]

![2017-06-01_1200](https://cloud.githubusercontent.com/assets/4663073/26688901/ef21bcf0-46c1-11e7-9aed-c9f246703e0c.png)

This displays as expected in Chrome and Firefox. In Safari, [All I Have to Give](http://dmcstudios.library.northeastern.edu/item/neu:cj82kv92d) displays as the first exhibit on the page:

![2017-06-01_1201](https://cloud.githubusercontent.com/assets/4663073/26688920/ffbe1d06-46c1-11e7-9114-8a839027d884.png)

This is true for the single item player and the media playlist. Using the tile gallery or other exhibit displays the correct file (presumably because it's using the thumbnail pid and not embedded media player?). 

The videos can not be played in Safari either (at least in my version of Safari, which I believe is up to date).

**Comment by elizoller** [comment]
This is fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/a4e4faa4922f432be4fca68de4245b002b04c21a
