### ISSUE TITLE
Unable to save editing changes:  Toolkit sites hosted on nb9313.neu.edu

### ISSUE THREAD

**Issue by KarlYee** [NEU-DSG/toolkit_requests#84]
At the moment, all Toolkit sites on nb9313.neu.edu are Archives related sites.

All features and functions on these sites appear to working, however,  any editing changes or new content can not be saved.  Any attempt to do so results in this error:
_"The connection has reset. The connection to the server has reset while the page was loading."_

Ernesto, David, and I have looked into this bug.  The consensus thus far is that it might be a network bug, possibly a firewall issue. In the mean time, users who want to edit Toolkit sites should make use of our proxy.  For example:
_http://ezproxy.neu.edu/login?url=http://voices.library.northeastern.edu_

Ernesto has taken the lead on this issue.

**Comment by sarahjeansweeney** [comment]
Caroline has just encountered the same issue or a similar issue in the EBBDA site: http://ebbda.northeastern.edu/

When she tries to update a WordPress page that uses the page builder she receives this message:

> This site can't be reached. ebbda.northeastern.edu took too long to respond.

FWIW, she is able to save pages that do not use the page builder.

This site is not one of the Toolkit sites that were recently moved to the Archives server (or, if it was, then it should not have been). Just in case, I tried to use the ezproxy URL construction above to log in to the EBBDA site, but received an error:

> There appears to be a problem with the library's access to the material you are trying to view. The host address is not recognized by the proxy server. Please follow the link below to report the problem to the library.

**Comment by KarlYee** [comment]
It’s a similar issue

A couple of things …  No, this site wasn’t moved over to nb9313.neu.edu.  It’s still on dsg.neu.edu (nb4656.neu.edu).

The proxy you’re referring to only works on the Toolkit sites on nb9313.neu.edu, for the moment.

The error message is different ..
The error message from the Voices site was “"The connection has reset. The connection to the server has reset while the page was loading." or "The site can't be reached. The connection was reset."

I’m copying this message over to Slack to loop in Ernesto and Greg.

Karl

**Comment by cklibanoff** [comment]
If it's helpful, here is the message I receive in Safari when this happens: "Safari can't open the page "ebbda.northeastern.edu/wp-admin/post.php" because the server where this page is located isn't responding."

**Comment by sarahjeansweeney** [comment]
I think this has been resolved through ezproxy/SSL/campus authentication changes. Can reopen if it's encountered again.
