### ISSUE TITLE
500 Internal Server Error accessing all toolkit sites

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#85]
Thomas just reported to me that he can't access the DMC Studios site (http://dmcstudios.library.northeastern.edu/). I can't access it or any of the other Toolkit sites, either. Attempting to connect to any Toolkit site returns a 500 Internal Server Error notice:

<img width="1225" alt="2017-07-14_1348" src="https://user-images.githubusercontent.com/4663073/28223947-56d7ca74-689b-11e7-86b2-14f51fe56691.png">

**Comment by ablevesque** [comment]
I'm having no issues on any sites from Chrome (somewhere in the Atlantic ocean.) Is the possibly related to our issues Thursday with Catskills and arader?

-Abbie
________________________________
