### ISSUE TITLE
Various issues accessing a handful of CERES sites

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#87]
I'm experiencing issues connecting to a few CERES sites (FWIW it's the end of the day and I haven't asked anyone else to confirm).

Many sites work as expected (bouve, thoreau, catskills), but others only partially load and I can't connect to ECDA at all.

**Partial Loading**
http://recordingstudios.library.northeastern.edu/
http://arader.library.northeastern.edu/
http://dragonprayerbook.northeastern.edu/

<img width="1225" alt="2017-09-26_1651" src="https://user-images.githubusercontent.com/4663073/30884117-63517b62-a2dc-11e7-9b36-978f28a10ec1.png">
<img width="1225" alt="2017-09-26_1654" src="https://user-images.githubusercontent.com/4663073/30884115-634f6d4a-a2dc-11e7-949b-8b1fe8e3bd4b.png">
<img width="1225" alt="2017-09-26_1656" src="https://user-images.githubusercontent.com/4663073/30884116-6350138a-a2dc-11e7-91f9-c58e1a3fad08.png">

**503 Error**
http://ecda.northeastern.edu/

<img width="1225" alt="2017-09-26_1702" src="https://user-images.githubusercontent.com/4663073/30884156-814e10c6-a2dc-11e7-8db7-412c77d5ac02.png">

Will check back tomorrow to make sure it wasn't a temporary blip.

**Comment by nestochan** [comment]
May have been a temporary blip as i'm not seeing this issue... on any of those sites.

**Comment by sarahjeansweeney** [comment]
Yup, they all work fine now! Thanks

**Comment by sarahjeansweeney** [comment]
Seeing this again right now (on wifi, seeing in both Chrome and Firefox):

http://arader.library.northeastern.edu/
<img width="1225" alt="2017-09-27_1235" src="https://user-images.githubusercontent.com/4663073/30925672-a25f0f00-a380-11e7-83d4-4e43e82316a9.png">

http://dragonprayerbook.northeastern.edu/
<img width="1225" alt="2017-09-27_1235-1" src="https://user-images.githubusercontent.com/4663073/30925677-a80b5d28-a380-11e7-9c83-16b460836686.png">
