### ISSUE TITLE
Can't open shortcodes settings in Firefox

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#89]
Kaley just reported that double-clicking the short code in an existing exhibit page doesn't work in Firefox.

To replicate, edit an exhibit page in Firefox (i.e. http://catskillsinstitute.northeastern.edu/exhibits/hotels-and-bungalows/timeline/) and open the exhibit visual editor to edit the short code. Double click the short code to open the "Add Toolkit Shortcodes" settings. Doing so in Firefox will only highlight the short code text that was clicked, rather than opening the menu:

![2017-10-12_1510](https://user-images.githubusercontent.com/4663073/31514446-a58a1b94-af5f-11e7-8f61-6a07674eb63d.png)

Double clicking the shortcode in Chrome does open the "Add Toolkit Shortcodes" settings.

**Comment by decampda** [comment]
I just tested this with Firefox (most recent version, for Mac) and I was able to double click the shortcode to edit the settings just fine.

**Comment by sarahjeansweeney** [comment]
This issue was reported to me again on Friday. The person encountered it while using Firefox v.59.0.2

**Comment by sarahjeansweeney** [comment]
I'm able to open the editor as expected in Firefox v.62.0

**Comment by mmwoods2019** [comment]
I am also able to double-click the shortcode using Firefox v.62.0
