### ISSUE TITLE
DRS Connection Issue?

### ISSUE THREAD

**Issue by colleencurtis** [NEU-DSG/toolkit_requests#9]
When navigating around the front end of the site, I suddenly received this error message when trying to connect to Browse or Collections pages. Other pages loaded, but their DRS images did not.

http://arader.library.northeastern.edu/collections/
![screen shot 2015-11-19 at 5 29 00 pm](https://cloud.githubusercontent.com/assets/15789920/11286509/4bd34470-8ee3-11e5-9ec2-877f69eb25fb.png)

**Comment by elizoller** [comment]
I think this was probably when David was deploying new code to the DRS which makes it unavailable for a few minutes.
Reopen this issue if you're still experiencing it.

**Comment by sarahjeansweeney** [comment]
That error message needs to be updated. Maybe something like, "Sorry, these project materials are currently unavailable. Please try again later."
