### ISSUE TITLE
Usability and other enhancements for CERES v.2

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#90]
* Move download options from the bottom of the item page to the top so users don't have to scroll down the page (some users assume there's nothing to download because they don't scroll on pages with lots of good metadata)
* Podcast feed support (i.e. add metadata to WordPress rss feed that will allow it to be validated by iTunes)
  * Apple updated their list of best practices for discoverability and user experience in June 2018 (https://help.apple.com/itc/podcasts_connect/#/itcb54353390), including:

> - Deliver clear, concise titles.
> - Number and recommend episodes (and even “pin” a trailer to the top of the feed).
> - Allow new subscribers to receive the full current season in their Library.
> - Allow users to pick up listening where they left off.

That[ What's New ](http://whatsnewpodcast.org/)feed will need to be updated to follow those new recommended practices

**Comment by dgcliff** [comment]
I'd much prefer if v2 didn't have scroll hijacking (comes with the theme, I think)

**Comment by sarahjeansweeney** [comment]
Suggested by @AmandaRust:
- Support full screen page image, like the [Phoenix homepage](https://phoenix.library.northeastern.edu/)
- Add option for left - justfied navigation menu, like the [Phoenix homepage](https://phoenix.library.northeastern.edu/)

**Comment by sarahjeansweeney** [comment]
Suggested by ECDA team:

- Add option to select historical base map
- Would like to be able to select the area of the page to place the custom text on item pages (they prefer the top right of the page, above the metadata, but if we do this customization I think it makes sense to assume that other groups may want custom text to appear in other areas)

**Comment by sarahjeansweeney** [comment]
The custom item text page doesn't seem to include the visual editor. If possible, the visual editor should be an option on these pages. (Another ECDA team request)

**Comment by cklibanoff** [comment]
Enhancement - adding capability for discussion forum (Thoreau Project)

**Comment by sarahjeansweeney** [comment]
Suggestion for HAC and Our Marathon projects:
The /collections path currently brings up all collections, including nested collections. We might want to consider having this page display the top-level collections only rather than all collections, including nested collections.

For example, for Arader: https://arader.library.northeastern.edu/collections

Rather than pulling up the list of all collections in the base URL: 

![2018-03-20_1448](https://user-images.githubusercontent.com/4663073/37676250-cab4d254-2c4d-11e8-9997-5feaa5fcdae0.png)

Just the top-level collections should display:
![2018-03-20_1448-1](https://user-images.githubusercontent.com/4663073/37676274-d80901e6-2c4d-11e8-9147-eea9494688ce.png)

Or, toggling between all collections and just top level collections could be a CERES setting.

**Comment by sarahjeansweeney** [comment]
From Jim M: 

> The WBUR Oral History Project pages display [Related Items](https://marathon.library.northeastern.edu/item/neu:m042f098x/) (which is cool!). Is there a way to display all related items on the page instead of one at a time?

This seems like a good idea - rather than paging through each item, either list all associated files or increase number of associated files on each page from 1 to 5 or 10

**Comment by sarahjeansweeney** [comment]
Increase contrast between metadata labels and values on the item pages. As it displays now, the metadata labels and values on item pages appear as text that is exact or very similar in color, size, and weight, which makes it difficult for the reader to scan the information on the page:

![2018-04-05_0949](https://user-images.githubusercontent.com/4663073/38370015-0de7f8e2-38b7-11e8-8d1b-4da2808eb863.png)

![2018-04-05_0950](https://user-images.githubusercontent.com/4663073/38370022-1385f754-38b7-11e8-9b42-e8afab1a16c0.png)

As an example, the DRS metadata contrast is very readable:

![2018-04-05_0953](https://user-images.githubusercontent.com/4663073/38370110-4d3a0cba-38b7-11e8-8172-069d9c295b1b.png)

The contrast between the labels and the values should be increased. (This may be customizable in the WordPress settings, but I think the labels and values should be more distinct out of the box.)

**Comment by AmandaRust** [comment]
Add the capability to embed sets within a CERES URL. Right now, collections bring up a lovely browse page: https://marathon.library.northeastern.edu/collection/neu:cj82qn471/ . It would give users more flexibility if DRS sets could be embedded the same way. This would (at the moment) help the Holocaust Awareness Committee.

**Comment by AmandaRust** [comment]
Add the capability to pass through fielded search. Right now, I can run a general search like https://marathon.library.northeastern.edu/search/?q=girdharry, but it would be great to also be able to specify creator= or title=. The use case for this is when CERES users want a method to generate a browse page that will dynamically update, so that for example you'd link to a browse page with creator=girdharry, and every time a new item was added with creator=girdharry it would automatically show up on that page, since the page is generated by a dynamic query. If there's a better way to accomplish this, that would be fine!

**Comment by sarahjeansweeney** [comment]
The shortcode menu pane should display a file's full title rather than a truncated version. The current setting works well for multiple files with short, unique titles, but not as well for multiple with files long, similar titles. For example, the Recording Studios site includes podcast episodes that are cataloged with the podcast series and the episode name in the title (this is the library's convention for cataloging podcast episodes - What's New uses this format as well). With the truncated text, it's hard to distinguish which episode is which:
![2018-05-11_1027](https://user-images.githubusercontent.com/4663073/39929788-f904d7bc-5506-11e8-80d9-15561ee783be.png)

The What's New site gets around this because they use unique thumbnails for each episode, but the same issue exists:
![2018-05-11_1034](https://user-images.githubusercontent.com/4663073/39929812-fd531022-5506-11e8-82a8-53c734737741.png)

**Comment by sarahjeansweeney** [comment]
Evaluate plugin/template for compliance with basic accessibility standards. Upgrade where necessary. 

Consider including a WP ADA compliance check plugin as a default plugin with every install, which could help steer users to make accessible design decisions (https://wordpress.org/plugins/wp-ada-compliance-check-basic/ suggested by Karl Y).

**Comment by sarahjeansweeney** [comment]
The default display for the browse page is a tile grid display of thumbnails. It's been suggested that this is not useful for sites focused mainly on text (ETD, Center for Labor Market Studies). To accommodate both text and other formats in browse, an option could be added to the CERES settings to select the default display for browse, either a grid display or a list display.

**Comment by sarahjeansweeney** [comment]
Some project teams would like to use a community as the base URL for CERES site. To accommodate this, it might be useful to expand the base URL options to include /communities paths or featured content URL paths, like:

- https://repository.library.northeastern.edu/theses_and_dissertations
- https://repository.library.northeastern.edu/research
- https://repository.library.northeastern.edu/presentations
- https://repository.library.northeastern.edu/communities/neu:6001

This change would be dependent on DRS API changes.

**Comment by AmandaRust** [comment]
I've split these all out for a move into PMJ's existing workspace -- closing this one out so w can retire this repo.
