### ISSUE TITLE
"Sorry, these project materials are currently unavailable." message when searching/browsing HAC site

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#91]
The search and browse functions for the Holocaust Awareness Archives site are currently not working: http://holocaustawarenessarchives.northeastern.edu/ (requires login)

Users encounter the following error message when clicking the "Browse" link in the top navigation menu and when performing a search:

> Sorry, these project materials are currently unavailable. Please try again later.

Browse:

![2017-10-30_1554](https://user-images.githubusercontent.com/4663073/32192684-41a3c046-bd8b-11e7-9722-08b79be34246.png)

Search:

![2017-10-30_1556](https://user-images.githubusercontent.com/4663073/32192693-47b6f41c-bd8b-11e7-833d-b0911482c72c.png)

Other aspects of the site are functional, including the "Related Content" WordPress search. I believe these errors indicate an issue reaching the API.

**Comment by nestochan** [comment]
@sarahjeansweeney are there any other TK sites that use this browse feature, where it's working?

**Comment by sarahjeansweeney** [comment]
@nestochan Yes, as far as I can tell it's working for all other sites, including:

http://arader.library.northeastern.edu/search?q=
http://phoenix.library.northeastern.edu/search/?q=
http://catskillsinstitute.northeastern.edu/browse/
http://thoreaudrawings.northeastern.edu/browse/

**Comment by sarahjeansweeney** [comment]
Fixed - from @nestochan : 

> SSL not fully forced on site. so admin components are all on SSL where other bits are not. when accessing a non SSL protected page that requires an admin level component that component is flagged as a XScripting Condition and rejected with a 403 error in the dev console. by forcing all aspects of site to use SSL - cleared up the issue.
