### ISSUE TITLE
Mirador not displaying page images

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#92]
The Dragon Prayer Book site is the only CERES site that uses the IIIF Mirador page image viewer: https://dragonprayerbook.northeastern.edu/mirador/

The project team reported yesterday that the page images are not displaying in the viewer:
![2017-11-08_0901](https://user-images.githubusercontent.com/4663073/32553045-c3e0aef0-c463-11e7-941c-a581d4325717.png)

**Comment by elizoller** [comment]
This is due to a mix of http and https
I updated the manifest to be https but loris isn't configured on https so it won't load the images

**Comment by nestochan** [comment]
@elizoller / @sarahjeansweeney I'll order a certificate for this... now besides the nb# does this host have a DNS/HostNAME? loris<dot>sammat<dot>sammat-else? 🃏   also is this served via apache?

**Comment by elizoller** [comment]
Yeah its run by apache with wsgi conf in /etc/httpd/conf.d/loris.conf
I dont think it had a hostname, all the notes I can dig up just call it nb9225

**Comment by nestochan** [comment]
OKIDOKI -- i've ordered a cert for nb9225 when it's approved i'll install and config for use with loris.conf

**Comment by nestochan** [comment]
OK - i've configured `SSL` on `nb9225` and adjusted firewall and restarted ... I believe dragonPBK is now loading.. tester 'er out... 🃏

**Comment by sarahjeansweeney** [comment]
Looks good - thanks!
