### ISSUE TITLE
Menu Text Run-off

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#95]
On the ECDA website longer text on dropdown menus runs off the dropdown box. There doesn't seem to be a way to expand the size of the dropdown box so longer titles don't run off.

![35287069-8fe510de-002f-11e8-882d-74c5f4978087](https://user-images.githubusercontent.com/4663073/35413146-851ffa10-01ec-11e8-8a0f-00e9a4fcb5b8.png)

(Just moving https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/issues/125 here)

**Comment by elizoller** [comment]
I would recommend to ECDA they place {white-space: nowrap;} on '.main-navigation .nav .dropdown-menu li a' in their custom CSS

**Comment by sarahjeansweeney** [comment]
Thanks, @elizoller! This works. For future reference, here's the CSS I used (with help from @amclark42 ):

.main-navigation .nav .dropdown-menu li a {white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
}
