### ISSUE TITLE
Can't Change Button Color

### ISSUE THREAD

**Issue by s-payne** [NEU-DSG/toolkit_requests#96]
When using the SiteOrigin Button widget on the ECDA site, the option to change the button color doesn't appear in the widget settings. 

![screen shot 2018-02-13 at 7 53 11 pm](https://user-images.githubusercontent.com/30182432/36182439-a7f82fc0-10f7-11e8-9329-68c60454e5ec.png)

**Comment by elizoller** [comment]
This is a conflict between Quest theme (our base theme) and the SiteOrigins Widget. I don't see an immediate fix when I dig into the Quest theme code that we could implement. Probably the easiest solution would be for them to create a CSS class that correlates to a specific button color and add that class in their custom CSS.

**Comment by sarahjeansweeney** [comment]
Thanks, @elizoller! This works. For future reference, here's the CSS I used (with help from @amclark42 ):

.main-navigation .nav .dropdown-menu li a {white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
}

**Comment by sarahjeansweeney** [comment]
Closed wrong issue :(

**Comment by AmandaRust** [comment]
I"ll work with the ECDA folks to see if this is still a current issue. I don't think we want to encourage CSS overrides for buttons, but maybe long-term we can work on finding a reasonable solution for this without relying on Site Origin so heavily.
