### ISSUE TITLE
DPLA Items not appearing on timeline

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#97]
Students in the fall Literature and Digital Diversity class reported that not all DPLA items were displaying on the timelines they were building. Here's a good summary of the problem from @saraheconnell :

> I tried adding a timeline with a random selection of Seattle-related items and only two of the seven appear. Here's the code:
> `[drstk_timeline id="dpla:6e7b4f73a28674239da9cf28c17e6be0,dpla:608f619501e97a09152b3c38abbd2729,dpla:c20124d533957659720b120079354760,dpla:137778f086644e8642b11cd09f877b18,dpla:aadfec85f0d4b744c4685c9597864b29,dpla:c2c6205e30884d8ab607950fe6a80a40,dpla:a86f9dd5ceab75e7b4d16b0c46efaae6" metadata="creator_tesim" increments="5" ]`
>  
> And, this is what you get:
> https://litdigitaldiversity.northeastern.edu/in-class-demo/
>  
> If you look at the bottom, you can see the timeline, with just the two items. 
>  
> I added these just by searching for "Seattle" in the DPLA search box and checking off a handful that had straightforward dates (skipping ones with ranges or "ca."). I left the rest of the settings at default.
>  
> [the shortcode for a different timeline built by a student] seems okay to me—I even tried re-creating a timeline using those DPLA items and leaving the rest of the settings as-is and I got the same result: no timeline. 

The reason some images are displaying and others aren't isn't immediately clear. As Sarah mentions, the date doesn't seem to affect the issue, though in my test exhibit the item that doesn't display has "20th century" as a date. I created this page to test the issue myself: http://liblab.neu.edu/drstest/timeline-issue/

There are two exhibits on that page, each with the same items from the DPLA. The timeline displays only three of the items, but the slider displays all four. The item that doesn't display is this item with "20th century" listed as the date: https://dp.la/item/49fe7db1e9752bd00bc1196880bc6ca0

Only items from the DPLA seem to be affected. In case it's relevant, @AmandaRust noticed that all the problem items in Sarah C's issue were coming from ContentDM hosted on OCLC.

**Comment by nestochan** [comment]
![screenshot 2018-02-15 13 51 05](https://user-images.githubusercontent.com/2441612/36275050-c026d572-1257-11e8-91fc-4f63a5d73790.png)

PID looks like it's missing the colon and giving up an error in the console.

**Comment by elizoller** [comment]
I'm guessing this is a metadata issue. Either its not parsing the dates being sent back from DPLA or there isn't sufficient enough date metadata. The parsing does the following - looks if the sourceRecord displayDate and splits it on the "-" (to see if its in "YYYY-MM-DD" format), it takes the first 4 and puts it as the year, the second two as the month or fills in 1, the last 2 as date or fills in 1. If the first segment isn't 4 digits long then it looks in the sourceRecord date begin field to see if that is populated. But since sourceRecords are as they sound, sourceRecords, dates are not necessarily standardized.
I'm looking into the specific examples you included above.

**Comment by elizoller** [comment]
Ahhhh it appears some records have the date values wrapped in an array and some do not. I'll see if I can modify to handle that.

**Comment by elizoller** [comment]
fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/2443326601e017bc66b990633a802295d45de79b
